version: '3'
services:
  laravel:
    build:
      context: ./backend
      dockerfile: docker/8.2/Dockerfile
    ports:
      - "9000:8000"   # 変更：PHP-FPMではなくartisan serveを使う
      - "9003:9003"
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      TZ: Asia/Tokyo
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    volumes:
      - ./backend:/var/www/html
    networks:
      - sail

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - sail

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - sail

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - sail

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "8001:5540" # open http://localhost:8001
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis
    networks:
      - sail
      
  nuxt:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - laravel
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redisinsight_data:
    driver: local
